version: '3.9'

networks:
  default:
    name: 'tfa'

volumes:
  tfa-pg:
  tfa-logs:
  tfa-prom:
  tfa-grafana:

services: 
  postgres:
    container_name: 'tfa-pg'
    image: 'postgres:latest'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: 'admin'
    volumes:
      - tfa-pg:/var/lib/postgresql/data

  loki:
    container_name: 'tfa-loki'
    image: 'grafana/loki'
    ports:
      - '3100:3100'
    volumes:
      - ./loki-config.yml:/etc/loki/local-config.yml
    command: --config.file=/etc/loki/local-config.yml

  prometheus:
    container_name: 'tfa-prom'
    image: 'prom/prometheus'
    ports:
      - '9090:9090'
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - tfa-prom:/prometheus

  jaeger:
    container_name: 'tfa-jaeger'
    image: 'jaegertracing/all-in-one:1.9'
    environment:
      COLLECTOR_ZIPKIN_HTTP_PORT: 9411
    ports:
      - '5775:5775/udp'
      - '6831:6831/udp'
      - '6832:6832/udp'
      - '5778:5778'
      - '16686:16686'
      - '9411:9411'

  grafana:
    container_name: 'tfa-grafana'
    image: 'grafana/grafana'
    restart: unless-stopped
    environment:
      GF_INSTALL_PLUGINS: 'grafana-clock-panel,grafana-simple-json-datasource'
    volumes:
      - tfa-grafana:/var/lib/grafana
    ports:
      - '3000:3000'
    depends_on:
      - prometheus

  api:
    build:
      context: .
    container_name: 'tfa-api'
    ports:
      - '8080:8080'
    environment:
      ASPNET_URLS: 'http://0.0.0.0:8080'
      ConnectionStrings__Postgres: "User ID=postgres;Password=admin;Host=tfa-pg;Port=5432;Database=tfa;Pooling=true;MinPoolSize=0;MaxPoolSize=100;Connection Idle Lifetime=60;"
      ConnectionStrings__Logs: "http://tfa-loki:3100"
      ConnectionStrings__Tracing: "http://tfa-jaeger:14268/api/traces"